apiVersion: v1
kind: ConfigMap
metadata:
  name: timeout-workflow-config
  namespace: sample-app-namespace-1752694887375
  labels:
    app.kubernetes.io/name: timeout-workflow
    kubernetes.azure.com/generator: devhub
data: