apiVersion: v1
kind: Service
metadata:
  name: gohttp
  namespace: default
  labels:
    app.kubernetes.io/name: gohttp
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: gohttp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80